'use strict';

module.exports = {
  kind: 'collectionType',
  collectionName: 'menu_items',
  info: {
    displayName: 'Menu Item',
    singularName: 'menu-item',
    pluralName: 'menu-items',
    tableName: 'menu_items',
  },
  options: {
    draftAndPublish: false,
  },
  pluginOptions: {
    'content-manager': {
      visible: false,
    },
    'content-type-builder': {
      visible: false,
    },
  },
  attributes: {
    order: {
      type: 'integer',
    },
    title: {
      type: 'string',
      required: true,
    },
    url: {
      type: 'string',
    },
    target: {
      type: 'enumeration',
      enum: [
        '_blank',
        '_parent',
        '_self',
        '_top',
      ],
    },
    root_menu: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'plugin::menus.menu',
      inversedBy: 'items',
      required: true,
    },
    parent: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'plugin::menus.menu-item',
    },

    /**
     * @TODO - Need a way to make the fields below configurable so the fields above
     * remain as "essential" fields and the rest can be customized by developers.
     */
    title_mobile: {
      type: 'string',
    },
    icon: {
      type: 'enumeration',
      enum: [
        'arrow_circle',
        'battery',
        'bike',
        'binoculars',
        'bookmark',
        'books',
        'briefcase',
        'building',
        'calculator',
        'camera',
        'camp',
        'canoe',
        'car',
        'chart_bar',
        'chart_pie',
        'circle',
        'close',
        'cloud',
        'comment_circle',
        'comment_rectangle',
        'comment',
        'compass',
        'credit_card',
        'crown',
        'discount',
        'dollar_bills',
        'dots',
        'envelope_open',
        'envelope',
        'faq',
        'finance',
        'fire',
        'gamepad',
        'garage',
        'graduation_cap',
        'grid_add',
        'grid',
        'hammer',
        'hand_holding_dollar',
        'hand_holding_seedling',
        'heart_hands',
        'heart',
        'helicopter',
        'hexagon',
        'house',
        'info',
        'laptop',
        'leaf',
        'lightbulb',
        'location_arrow',
        'lock_open',
        'lock',
        'map_marker_dot',
        'map_marker',
        'mobile',
        'monitor',
        'motor_home',
        'mouse',
        'palm_tree',
        'path',
        'phone',
        'plane',
        'polaroid',
        'power',
        'rocket',
        'scooter_electric',
        'scooter_push',
        'scooter_vespa',
        'screwdriver',
        'search',
        'shield_award',
        'shield_security',
        'ship',
        'smile_beam',
        'smile_stars',
        'speedometer',
        'square',
        'star',
        'sun',
        'suv',
        'tachometer',
        'tag',
        'target',
        'timer_fast',
        'timer',
        'toolbox',
        'tools',
        'trophy',
        'truck',
        'tune',
        'upload',
        'user_circle',
        'users_2',
        'users_3',
        'ute',
        'van',
        'wallet',
        'watch_apple',
        'watch'
      ],
    },
    page: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::page.page',
    },
    post: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::post.post',
    },
    post_category: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::post-category.post-category',
    },
    faq: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::faq.faq',
    },
    help: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::help.help',
    },
    loan: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::loan.loan',
    },
  },
};
